### ISSUE TITLE
Remove all unused functions (get, set)

### ISSUE THREAD

**Issue by Hiaza** [andreyTheGreatest/mipz_lab1#1]
In City.java
![image](https://user-images.githubusercontent.com/36272398/172732781-df167fec-04da-43f7-9278-22bc21f28b28.png)

Same in CountryCoords.java
![image](https://user-images.githubusercontent.com/36272398/172732904-3ddd4d4f-fccf-4cdf-9f17-476c7dbcf988.png)

And remove extra ; - [here](https://github.com/andreyTheGreatest/mipz_lab1/blob/main/src/main/java/Main.java#L33)

**Comment by andreyTheGreatest** [comment]
a lot of unused code, yes
