### ISSUE TITLE
Move or remove class Coords

### ISSUE THREAD

**Issue by Hiaza** [andreyTheGreatest/mipz_lab1#3]
Remove class Coords, because of making things more complicated and creating extra imports. https://github.com/andreyTheGreatest/mipz_lab1/blob/main/src/main/java/models/grid/MapGrid.java#L59 
instead of get(Coords coords) -> get(int x, int y).

Or make Coords as inner class of Grid, because it's only using there.

**Comment by andreyTheGreatest** [comment]
Coupling Coords class with a Grid makes sense in this issue's context
