### ISSUE TITLE
Add a few missed rules

### ISSUE THREAD

**Issue by Hiaza** [andreyTheGreatest/mipz_lab1#6]
> The first line of each test case is the number of countries (1 ≤ c ≤ 20)

Need to validate the number of countries by adding new constant - [here](https://github.com/andreyTheGreatest/mipz_lab1/blob/main/src/main/java/models/Parser.java#L18)

> For each test case, print a line indicating the case number, followed by a line for each country with the country name and number of days for that country to become complete. Order the countries by days to completion. If two countries have identical days to completion, order them alphabetically by name

Need to add this sort, I guess [here](https://github.com/andreyTheGreatest/mipz_lab1/blob/main/src/main/java/models/grid/MapGrid.java#L87)  

Rename the [function](https://github.com/andreyTheGreatest/mipz_lab1/blob/main/src/main/java/models/Country.java#L30) according to the naming convention, for example to the **areCoordsValid**.

**Comment by andreyTheGreatest** [comment]
good catch
