### ISSUE TITLE
Remove local?

### ISSUE THREAD

**Issue by IanaKhitsko** [andreyTheGreatest/mipz_lab1#9]
https://github.com/andreyTheGreatest/mipz_lab1/blob/c1d59fedd6eadf2b3f486617682614d8c1db479b/src/main/java/models/grid/MapGrid.java#L82

Why do we need this local here? Can we use currDay?

**Comment by andreyTheGreatest** [comment]
Apparently these lamda java expressions work with finalazied local variables only, otherwise it won't start :(
![image](https://user-images.githubusercontent.com/36274310/174538788-bdf51881-a405-41b9-b8da-fda13d27d953.png)
